services:
  discover-server:
    build:
      context: ../io.discovery/discover-server
      dockerfile: Dockerfile
    image: ryanjayf/discover-server:v1
    container_name: discover-server
    ports:
      - "${DISCOVERY_SERVER_PORT}:8761"
    networks:
      - my_network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://discover-server:8761/actuator/health"]  # Access via service name
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  config-server:
    build:
      context: ../io.configserver/config-server
      dockerfile: Dockerfile
    image: ryanjayf/configserver:v1
    container_name: configserver
    ports:
      - "${CONFIG_SERVER_PORT}:8888"
    networks:
      - my_network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discover-server:8761/eureka
    depends_on:
      discover-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://configserver:8888/actuator/health"]  # Access via service name
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  service:
    build:
      context: ../io.service/service
      dockerfile: Dockerfile
    image: ryanjayf/service:v1
    container_name: service
    ports:
      - "${SERVICE_PORT}:8085"
    networks:
      - my_network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONFIG_URI=http://configserver:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discover-server:8761/eureka
    depends_on:
      discover-server:
        condition: service_healthy
      config-server:
        condition: service_healthy

networks:
  my_network:
    driver: bridge
    external: true
